#!/usr/bin/env python

import pygal_maps_world as worldmap

country_dict = {
    "Andorra": "ad", 
    "United Arab Emirates": "ae", ""
    "Afghanistan": "af", "Albania": "al",
    "Armenia": "am", 
    "Angola": "ao", 
    "Antarctica": "aq", 
    "Argentina": "ar", 
    "Austria": "at",
    "Australia": "au", 
    "Azerbaijan": "az", 
    "Bosnia and Herzegovina": "ba", 
    "Bangladesh": "bd",
    "Belgium": "be", 
    "Burkina Faso": "bf", 
    "Bulgaria": "bg", 
    "Bahrain": "bh", 
    "Burundi": "bi",
    "Benin": "bj", 
    "Brunei": "bn", 
    "Bolivia": "bo", 
    "Brazil": "br", 
    "Bhutan": "bt",
    "Botswana": "bw", 
    "Belarus": "by", 
    "Belize": "bz", 
    "Canada": "ca", 
    "Democratic Republic of Congo": "cd",
    "Central African Republic": "cf", 
    "Republic of Congo": "cg", 
    "Switzerland": "ch",
    "Côte d'Ivoire": "ci", 
    "Chile": "cl", 
    "Cameroon": "cm", 
    "China": "cn", 
    "Colombia": "co",
    "Costa Rica": "cr", 
    "Cuba": "cu", 
    "Cape Verde": "cv", 
    "Cyprus": "cy", 
    "Czech Republic": "cz",
    "Germany": "de", 
    "Djibouti": "dj", 
    "Denmark": "dk", 
    "Dominican Republic": "do", 
    "Algeria": "dz",
    "Ecuador": "ec", 
    "Estonia": "ee", 
    "Egypt": "eg", 
    "Western Sahara": "eh", 
    "Eritrea": "er",
    "Spain": "es", 
    "Ethiopia": "et", 
    "Finland": "fi", 
    "France": "fr", 
    "Gabon": "ga",
    "United Kingdom": "gb", 
    "Georgia": "ge", 
    "French Guiana": "gf", 
    "Ghana": "gh", 
    "Greenland": "gl",
    "Gambia": "gm", 
    "Guinea": "gn", 
    "Equatorial Guinea": "gq", 
    "Greece": "gr", 
    "Guatemala": "gt",
    "Guam": "gu", 
    "Guinea-Bissau": "gw", 
    "Guyana": "gy", 
    "Hong Kong": "hk", 
    "Honduras": "hn",
    "Croatia": "hr", 
    "Haiti": "ht", 
    "Hungary": "hu", 
    "Indonesia": "id", 
    "Ireland": "ie",
    "Israel": "il", 
    "India": "in_", 
    "Iraq": "iq", 
    "Iran": "ir", 
    "Iceland": "is_", 
    "Italy": "it",
    "Jamaica": "jm", 
    "Jordan": "jo", 
    "Japan": "jp", 
    "Kenya": "ke", 
    "Kyrgyzstan": "kg",
    "Cambodia": "kh", 
    "North Korea": "kp", 
    "South Korea": "kr", 
    "Kuwait": "kw", 
    "Kazakhstan": "kz",
    "Laos": "la", 
    "Lebanon": "lb", 
    "Liechtenstein": "li", 
    "Sri Lanka": "lk", 
    "Liberia": "lr",
    "Lesotho": "ls", 
    "Lithuania": "lt", 
    "Luxembourg": "lu", 
    "Latvia": "lv", 
    "Libya": "ly",
    "Morocco": "ma", 
    "Monaco": "mc", 
    "Moldova": "md", 
    "Montenegro": "me", 
    "Madagascar": "mg",
    "North Macedonia": "mk", 
    "Mali": "ml", 
    "Myanmar": "mm", 
    "Mongolia": "mn", 
    "Macau": "mo",
    "Mauritania": "mr", 
    "Malta": "mt", 
    "Mauritius": "mu", 
    "Maldives": "mv", 
    "Malawi": "mw",
    "Mexico": "mx", 
    "Malaysia": "my", 
    "Mozambique": "mz", 
    "Namibia": "na", 
    "Niger": "ne",
    "Nigeria": "ng", 
    "Nicaragua": "ni", 
    "Netherlands": "nl", 
    "Norway": "no", 
    "Nepal": "np",
    "New Zealand": "nz", 
    "Oman": "om", 
    "Panama": "pa", 
    "Peru": "pe", 
    "Papua New Guinea": "pg",
    "Philippines": "ph", 
    "Pakistan": "pk", 
    "Poland": "pl", 
    "Puerto Rico": "pr", 
    "Palestine": "ps",
    "Portugal": "pt", 
    "Paraguay": "py", 
    "Réunion": "re", 
    "Romania": "ro", 
    "Serbia": "rs",
    "Russia": "ru", 
    "Rwanda": "rw", 
    "Saudi Arabia": "sa", 
    "Seychelles": "sc", 
    "Sudan": "sd",
    "Sweden": "se", 
    "Singapore": "sg", 
    "Saint Helena": "sh", 
    "Slovenia": "si", 
    "Slovakia": "sk",
    "Sierra Leone": "sl", 
    "San Marino": "sm", 
    "Senegal": "sn", 
    "Somalia": "so", 
    "Suriname": "sr",
    "São Tomé and Príncipe": "st", 
    "El Salvador": "sv", 
    "Syria": "sy", 
    "Eswatini": "sz",
    "Chad": "td", 
    "Togo": "tg", 
    "Thailand": "th", 
    "Tajikistan": "tj", 
    "Timor-Leste": "tl",
    "Turkmenistan": "tm", 
    "Tunisia": "tn", 
    "Turkey": "tr", 
    "Taiwan": "tw", 
    "Tanzania": "tz",
    "Ukraine": "ua", 
    "Uganda": "ug", 
    "United States": "us", 
    "Uruguay": "uy", 
    "Uzbekistan": "uz",
    "Vatican City": "va", 
    "Venezuela": "ve", 
    "Vietnam": "vn", 
    "Yemen": "ye", 
    "Mayotte": "yt",
    "South Africa": "za", 
    "Zambia": "zm", 
    "Zimbabwe": "zw"
}

countries = country_dict.values()


def initialize_country_count()-> dict:
    country_count = {}
    for country in countries:
        country_dict[country] = 0
    return country_count


def main():
    pass


if __name__ == "__main__":
    main()