---
title: "Making_music_database"
output: html_document
date: "2026-02-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Going into the repository
```{r}
setwd("C:/Users/sjeng/OneDrive - The University of Texas at Austin/Coding/Music_Display/playlist_files/")
```

Loading in one file example
```{r}
file <- read.csv("01-2025.csv")
head(file)
```

Taking the column names and using them to create an empty dataframe
```{r}
col_names <- colnames(file)
col_names
#first creates a matrix of the same column length and then makes it a data frame
all_data <- data.frame(matrix(nrow = 0, ncol = length(col_names)))
colnames(all_data) <- col_names
```
Creating a function to take in all files in this directory and add all their data to the data frame along with the playlist name
```{r}
add_to_dataframe <- function(data_frame){
    data_frame_buffer <- data_frame
    files_list <- list.files()
    files_list[1]
    for (i in 1:2){ # length(files_list
        filename <- gsub(x = files_list[1], 
                         pattern = "\\.csv", 
                         replacement = "")
        
    }
}
add_to_dataframe(all_data)
```


